### ISSUE TITLE
bc1qm34lsc65zpw79lxes69zkqmk6ee3ewf0j77s3h

### ISSUE THREAD

**Issue by Erraiser9090** [BushidoUK/Ransomware-Tool-Matrix#25]
bc1qm34lsc65zpw79lxes69zkqmk6ee3ewf0j77s3h

**Comment by Erraiser9090** [comment]
bc1qm34lsc65zpw79lxes69zkqmk6ee3ewf0j77s3h

**Comment by BushidoUK** [comment]
Lmao, just a Binance Hot Wallet BTC address

![image](https://github.com/user-attachments/assets/69ef0c48-fa89-4c0c-93f6-29dfe510bef0)

https://platform.arkhamintelligence.com/explorer/address/bc1qm34lsc65zpw79lxes69zkqmk6ee3ewf0j77s3h
